examples/jsf/pastecode/src/main/java/org/jboss/weld/examples/pastecode/model/CodeFragment.java
/*
 * JBoss, Home of Professional Open Source
 * Copyright 2009, Red Hat, Inc., and individual contributors
 * by the @authors tag. See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jboss.weld.examples.pastecode.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Size;
import java.text.SimpleDateFormat;
import java.util.Date;

import static javax.persistence.GenerationType.AUTO;

/**
 * The entity class for the pasted code "fragment". This is the main entity
 * class in the application.
 *
 * @author Martin Gencur
 * @author Pete Muir
 */
@Entity
public class CodeFragment {

    private static final long MS_PER_SECOND = 1000;
    private static final long MS_PER_MINUTE = 60 * MS_PER_SECOND;
    private static final long MS_PER_HOUR = 60 * MS_PER_MINUTE;
    private static final long MS_PER_DAY = 24 * MS_PER_HOUR;

    private static final SimpleDateFormat df = new SimpleDateFormat("d MMM");

    @Id
    @GeneratedValue(strategy = AUTO)
    @Column(name = "id")
    private int id;

    @Temporal(TemporalType.TIMESTAMP)
    private Date datetime;

    @Enumerated(EnumType.STRING)
    private Language language;

    @Lob
    @Size(min = 1, message = "Must enter some text!")
    private String text;

    private String user;

    private String hash;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getHash() {
        return hash;
    }

    public void setHash(String hash) {
        this.hash = hash;
    }

    public Date getDatetime() {
        return this.datetime;
    }

    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    public String getFriendlyDate() {
        if (getDatetime() == null)
            return "unknown";

        Date now = new Date();

        long age = now.getTime() - getDatetime().getTime();

        long days = (long) Math.floor(age / MS_PER_DAY);
        age -= (days * MS_PER_DAY);
        long hours = (long) Math.floor(age / MS_PER_HOUR);
        age -= (hours * MS_PER_HOUR);
        long minutes = (long) Math.floor(age / MS_PER_MINUTE);

        if (days < 7) {
            StringBuilder sb = new StringBuilder();

            if (days > 0) {
                sb.append(days);
                sb.append(days > 1 ? " days " : " day ");
            }

            if (hours > 0) {
                sb.append(hours);
                sb.append(hours > 1 ? " hrs " : " hr ");
            }

            if (minutes > 0) {
                sb.append(minutes);
                sb.append(minutes > 1 ? " minutes " : " minute ");
            }

            if (hours == 0 && minutes == 0) {
                sb.append("just now");
            } else {
                sb.append("ago");
            }

            return sb.toString();
        } else {
            return df.format(getDatetime());
        }
    }

    public Language getLanguage() {
        return language;
    }

    public void setLanguage(Language language) {
        this.language = language;
    }

    public String getText() {
        return this.text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getUser() {
        return this.user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    @Override
    public String toString() {
        return "At " + getFriendlyDate() + " by " + getUser();
    }
}

examples/jsf/pastecode/src/main/java/org/jboss/weld/examples/pastecode/model/Language.java
/**
 *
 */
package org.jboss.weld.examples.pastecode.model;


public enum Language {

    TEXT("txt", "Plain text", "text"),
    AS3("as3", "AS3", "as3"),
    BASH("sh", "Bash", "bash"),
    CSHARP("cs", "C#", "csharp"),
    COLD_FUSION("cf", "Cold Fusion", "coldfusion"), CPLUSPLUS("cpp", "C++", "cpp"),
    CSS("css", "CSS", "css"),
    DELPHI("pas", "Delphi", "pas"),
    DIFF("diff", "Diff", "diff"), ERLANG("erl", "Erlang", "erl"),
    GROOVY("groovy", "Groovy", "groovy"),
    JAVASCRIPT("js", "JavaScript", "js"),
    JAVA("java", "Java", "java"),
    JAVAFX("fx", "JavaFX", "javafx"),
    PERL("perl", "Perl", "perl"),
    PHP("php", "PHP", "php"),
    POWER_SHELL("ps1", "Power Shell", "powershell"),
    PYTHON("py", "Python", "py"),
    RUBY("rb", "Ruby", "rb"),
    SCALA("scl", "Scala", "scala"),
    SQL("sql", "Sql", "sql"),
    VISUAL_BASIC("vb", "Visual Basic", "vb"),
    XML("xml", "XML", "xml");

    private final String extension;
    private final String name;
    private final String brush;

    Language(String extension, String name, String brush) {
        this.extension = extension;
        this.name = name;
        this.brush = brush;
    }

    public String getBrush() {
        return brush;
    }

    public String getExtension() {
        return extension;
    }

    public String getName() {
        return name;
    }
}

examples/jsf/pastecode/src/main/java/org/jboss/weld/examples/pastecode/servlets/DownloadServlet.java
/*
 * JBoss, Home of Professional Open Source
 * Copyright 2009, Red Hat, Inc., and individual contributors
 * by the @authors tag. See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jboss.weld.examples.pastecode.servlets;

import org.jboss.weld.examples.pastecode.model.CodeFragment;
import org.jboss.weld.examples.pastecode.session.CodeFragmentManager;

import javax.inject.Inject;
import javax.servlet.ServletException;
import javax.servlet.ServletOutputStream;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Servlet that offers the code fragment for download as a file
 *
 * @author Martin Gencur
 */
@WebServlet("/download")
public class DownloadServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Inject
    private Logger log;

    @Inject
    private CodeFragmentManager codeFragmentManager;

    @Override
    public void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        String id = request.getParameter("id");
        CodeFragment c = codeFragmentManager.getCodeFragment(id);
        String fileName = c.getUser() + "." + c.getLanguage();
        String txt = c.getText();

        response.setContentType("text/plain");
        response.addHeader("Content-Disposition", "attachment; filename=\"" + fileName + "\"");
        response.setContentLength(txt.length());

        ServletOutputStream out = response.getOutputStream();
        try {
            out.print(txt);
        } catch (Exception e) {
            log.log(Level.WARNING, "Error processing file for download", e);
        } finally {
            out.close();
        }

    }
}

examples/jsf/pastecode/src/main/webapp/display.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core">
  
  <ui:composition template="template.xhtml">
     <ui:define name="viewMetadata">
       <f:metadata>
         <!-- Bind the id to the pasteWindow, this allows us to load the correct fragment -->
         <f:viewParam name="id" value="#{pasteWindow.codeFragmentId}"/>
         <!-- Ask for the fragment to be loaded -->
         <f:event type="preRenderView" listener="#{pasteWindow.loadCodeFragment}"/>
       </f:metadata>      
    </ui:define>    
  
  	<ui:define name="myscripts">
		<!-- Include required JS files -->
		<ui:include src="jsScripts.xhtml"/>
	</ui:define>
	
  	<ui:define name="themes">
  		<link href="syntaxhighlighter/styles/shCore.css" rel="stylesheet" type="text/css" />
		<link rel="stylesheet" href="syntaxhighlighter/styles/shThemeDefault.css" type="text/css" title="Default Theme" media="screen"/>
		<link rel="alternate stylesheet" href="syntaxhighlighter/styles/shThemeEclipse.css" type="text/css" title="Eclipse Theme" media="screen"/>
		<link rel="alternate stylesheet" href="syntaxhighlighter/styles/shThemeEmacs.css" type="text/css" title="Emacs Theme" media="screen"/>
		<link rel="alternate stylesheet" href="syntaxhighlighter/styles/shThemeFadeToGray.css" type="text/css" title="FadeToGray Theme" media="screen"/>
		<link rel="alternate stylesheet" href="syntaxhighlighter/styles/shThemeMidnight.css" type="text/css" title="Midnight Theme" media="screen"/>
		<link rel="alternate stylesheet" href="syntaxhighlighter/styles/shThemeRDark.css" type="text/css" title="Dark Theme" media="screen"/>
		<link rel="alternate stylesheet" href="syntaxhighlighter/styles/shThemeDjango.css" type="text/css" title="Django Theme" media="screen"/>
  	</ui:define>

   	<ui:define name="mainarea">
	   	<div class="contentHeader">
	   	  Posted by #{pasteWindow.codeFragment.user} <h:outputText value="on" rendered="#{pasteWindow.codeFragment.friendlyDate != 'just now'}" /> #{pasteWindow.codeFragment.friendlyDate}
	   	  <div style="float:right">
  	  	  <a href="download?id=#{pasteWindow.codeFragment.hash == null ? pasteWindow.codeFragment.id : pasteWindow.codeFragment.hash}" style="text-decoration: none;">DOWNLOAD</a>
  	  	</div>
	   	</div>

      <div class="formRow">   		   		    
  			<h:outputLabel for="theme" value="Choose theme: "/>   
		   	<h:selectOneMenu id="theme" value="#{pasteWindow.theme}" onchange="chooseStyle(this.value);"> <!-- this.form.submit() -->		
		   	  <f:selectItems value="#{themes}" var="theme" itemLabel="#{theme.name}" itemValue="#{theme.name}" />
			  </h:selectOneMenu>
			</div>
			  
			<!--h:outputLabel for="unwrap" value="Unwrap code: "/>   
			<h:selectBooleanCheckbox id="unwrap" onchange="unwrap('codearea');"/-->
		   		
   		<div class="displayCode">
   			<pre class="brush: #{pasteWindow.codeFragment.language.brush}">#{pasteWindow.codeFragment.text}</pre>	
   		</div>
		   		
   	</ui:define>
   	
    <ui:define name="rightmenu">
   		<ui:include src="rightMenuDefault.xhtml"/>
   	</ui:define> 
    
  </ui:composition>
</html>

examples/jsf/pastecode/src/main/webapp/help.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core">
  
  <ui:composition template="template.xhtml">
   	
  <ui:define name="mainarea">
	<div style="width: 100%; padding: 7px;">
		
	   	<div class="contentHeader">Useful Information</div>
	   	
	   	<h3>Paste Code:</h3>
	   	
	   	<ul>
	   	 <li>Enter your nick - this is optional, if omitted, your paste will be anonymous</li>
	   	 <li>Choose the language of your code - this allows syntax highlighting</li>
	   	 <li>Choose if this code is private - when this option is chosen the application will generate a hash value of your code and will provide you with
	   	 a unique link (something like http://localhost:8080/weld-pastecode/582ad4). Furthemore your code will not be
	   	 listed in the right panel and cannot be found through the search.</li>
	   	 <li>Enter your code - you can also add a note</li>
	   	 <li>Submit the form!</li>  
	   	</ul>
	   	
	   	<h3>Search Pastes:</h3>
	   	<ul>
	   		<li>Go to a history page - now you can see all the posts with pagination</li>
	   		<li>You can narrow down the pastes by using the search form</li>
	   	</ul>
	   		   	
	   	<h3>Weld Features Covered:</h3>
	   	
	   	<ul>
	   		<li>Injection into POJO, EJBs and Servlets</li>
	   		<li>Use of WAR packaging</li>
	   		<li>Producers</li>
	   		<li>JPA access</li>
	   		<li>Decorators</li>
	   	</ul>
	   	<br/><br/>
	   	
	   	<strong>Enjoy working with Weld!</strong>
	   			 
	</div>
  </ui:define>
   	
  <ui:define name="rightmenu">
	  <ui:include src="rightMenuDefault.xhtml"/>
  </ui:define>
    
  </ui:composition>
  
</html>

examples/jsf/pastecode/src/main/webapp/history.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">

<ui:composition template="template.xhtml">
	<ui:define name="viewMetadata">
		<f:metadata>
			<f:viewParam name="page" value="#{history.page}" />
			<f:event type="preRenderView" listener="#{history.load}" />
		</f:metadata>
	</ui:define>

	<ui:define name="themes"/>

	<ui:define name="mainarea">
	
		<div class="paging">
		  <ui:include src="pagination.xhtml"/>
		</div>
		
		<ui:repeat value="#{history.codes}" var="codeFragment">
	   	<div class="contentHeader">
	   	  <span>Posted by </span>
	   	  <h:outputLink id="user" value="#{codeFragment.id}">
  			  <!-- display.jsf?id= -->
  				<h:outputText value="#{codeFragment.user}"></h:outputText>
	  		</h:outputLink>
	  		<span> on </span>
				<h:outputText id="datetime" value="#{codeFragment.datetime}">
          <f:convertDateTime type="both" pattern="d MMM yyyy 'at' h:mma" />
				</h:outputText>

        <div style="float:right">
					Language: #{codeFragment.language.name}
			  </div>
	   	</div>		
		
			<h:outputText value="Code (truncated): " />

			<div class="historyCode">
        <pre>
	  	    <h:outputText value="#{codeFragment.text}">
  		      <f:converter converterId="truncatingConverter"/>   
			    </h:outputText>
			  </pre>
			</div>

		</ui:repeat>
		
		<div class="paging">
		  <ui:include src="pagination.xhtml"/>
		</div>

	</ui:define>

	<ui:define name="rightmenu">

		<div class="searchParams">
      <div class="searchParamsHeader">Refine search</div>

      <div class="searchParam">
			  <h:outputLabel for="user" value="User:"/>
			  <h:inputText id="user" maxlength="30" value="#{history.codeFragmentPrototype.user}" />
		  </div>

      <div class="searchParam">
			  <h:outputLabel for="language" value="Language:" />
			  <h:selectOneMenu id="language" value="#{history.codeFragmentPrototype.language}">
			     <f:selectItem itemLabel="Any" itemValue="" />
				  <f:selectItems value="#{languages}" var="language"
					  itemLabel="#{language.name}" itemValue="#{language}" />
			  </h:selectOneMenu>
			</div>

      <div class="searchParam">
			  <h:outputLabel for="pasteDate" value="Date: " />
			  <h:inputText value="#{history.codeFragmentPrototype.datetime}" id="pasteDate"
				  alt="yyyy-mm-dd" title="yyyy-mm-dd"
				  converterMessage="Enter date formatted as yyyy-mm-dd !">
				  <f:convertDateTime type="date" pattern="yyyy-MM-dd" />
			  </h:inputText>
			</div>

      <div class="searchParam">
			  <h:outputLabel for="code" value="Code:" style="width:100%;"/>
			  <h:inputTextarea id="code" maxlength="30" rows="2"
				  value="#{history.codeFragmentPrototype.text}">
				  <f:validateBean disabled="true" />
        </h:inputTextarea>
      </div>

      <div class="searchParamButtons">
	  	  <h:commandButton action="#{history.newSearch}" image="img/search.png"/>
	  	</div>

  		<h:message for="pasteDate" />
  		
  		<br style="clear:both"/>
    </div>

	</ui:define>

</ui:composition>
</html>

examples/jsf/pastecode/src/main/webapp/home.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core">
  
   <ui:composition template="template.xhtml">
   	
      <ui:define name="mainarea">
	   			   		
         <div class="contentHeader">Post a new PasteCode <h:messages style="color: red" /></div>
	   		
         <h:inputTextarea id="text" styleClass="pastecode" value="#{pasteWindow.codeFragment.text}"/>

         <div class="formRow">
            <h:outputLabel for="language" value="Syntax highlighting"/>   
            <h:selectOneMenu id="language" value="#{pasteWindow.codeFragment.language}">		
               <f:selectItems value="#{languages}" var="language" itemLabel="#{language.name}" itemValue="#{language}" />
            </h:selectOneMenu>
         </div>

         <div class="formRow">
            <h:outputLabel for="exposure" value="Exposure"/>
            <h:selectOneMenu id="exposure" value="#{pasteWindow.privateFragment}">
               <f:selectItem itemValue="#{true}" itemLabel="Private"/>
               <f:selectItem itemValue="#{false}" itemLabel="Public"/>
            </h:selectOneMenu>
         </div>
	    
         <div class="formRow">
            <h:outputLabel for="user" value="Name / title"/>   		
            <h:inputText id="user" maxlength="30" size="30" value="#{pasteWindow.codeFragment.user}"/>
         </div>

         <div class="formButtons">
            <h:commandButton action="#{pasteWindow.send}" id="send" image="img/submit.png"/>
         </div>
	   	
         <br style="clear:both"/>
	   		
      </ui:define>
   	
      <ui:define name="rightmenu">
         <ui:include src="rightMenuDefault.xhtml"/>
      </ui:define>
    
   </ui:composition>
  
</html>

examples/jsf/pastecode/src/main/webapp/jsScripts.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:mj="http://mojarra.dev.java.net/mojarra_ext"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
      
	<ui:composition>
	
		<script type="text/javascript" src="syntaxhighlighter/src/shCore.js"></script>
		<script type="text/javascript" src="syntaxhighlighter/scripts/shBrushJScript.js"></script>
		<script type="text/javascript" src="syntaxhighlighter/scripts/shBrushJava.js"></script>
		<script type="text/javascript" src="syntaxhighlighter/scripts/shBrushAS3.js"></script>
		<script type="text/javascript" src="syntaxhighlighter/scripts/shBrushBash.js"></script>
		<script type="text/javascript" src="syntaxhighlighter/scripts/shBrushCSharp.js"></script>
		<script type="text/javascript" src="syntaxhighlighter/scripts/shBrushColdFusion.js"></script>
		<script type="text/javascript" src="syntaxhighlighter/scripts/shBrushCss.js"></script>
		<script type="text/javascript" src="syntaxhighlighter/scripts/shBrushCpp.js"></script>
		<script type="text/javascript" src="syntaxhighlighter/scripts/shBrushDelphi.js"></script>
		<script type="text/javascript" src="syntaxhighlighter/scripts/shBrushErlang.js"></script>
		<script type="text/javascript" src="syntaxhighlighter/scripts/shBrushDiff.js"></script>
		<script type="text/javascript" src="syntaxhighlighter/scripts/shBrushGroovy.js"></script>
		<script type="text/javascript" src="syntaxhighlighter/scripts/shBrushJavaFX.js"></script>
		<script type="text/javascript" src="syntaxhighlighter/scripts/shBrushPerl.js"></script>
		<script type="text/javascript" src="syntaxhighlighter/scripts/shBrushPhp.js"></script>
		<script type="text/javascript" src="syntaxhighlighter/scripts/shBrushPlain.js"></script>
		<script type="text/javascript" src="syntaxhighlighter/scripts/shBrushPowerShell.js"></script>
		<script type="text/javascript" src="syntaxhighlighter/scripts/shBrushPython.js"></script>
		<script type="text/javascript" src="syntaxhighlighter/scripts/shBrushRuby.js"></script>
		<script type="text/javascript" src="syntaxhighlighter/scripts/shBrushScala.js"></script>
		<script type="text/javascript" src="syntaxhighlighter/scripts/shBrushSql.js"></script>
		<script type="text/javascript" src="syntaxhighlighter/scripts/shBrushVB.js"></script>
		<script type="text/javascript" src="syntaxhighlighter/scripts/shBrushXml.js"></script>	
		<script type="text/javascript" src="functions.js"/>	
		<script type="text/javascript">
		     SyntaxHighlighter.all()
		</script>
		
	</ui:composition>
	b	
</html>

examples/jsf/pastecode/src/main/webapp/pagination.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

	<ui:composition>
	
		<ui:fragment rendered="#{history.paginator.pagesCount gt 1}">
		
      <span>Page #{history.paginator.page + 1} of #{history.paginator.pagesCount}</span>
      
		  <div style="float:right">				
		    <ui:fragment rendered="#{history.paginator.page ge 1}">
  				<a href="history.jsf?page=#{(history.paginator.page-1)}" class="pagination">Prev</a>
  		  </ui:fragment>
				
				<ui:repeat var="page" value="#{history.paginator.indexes}">
				  <ui:fragment rendered="#{history.paginator.page eq page}">
				    <span class="currentPage">#{page+1}</span>
				  </ui:fragment>
				  <ui:fragment rendered="#{history.paginator.page ne page}">
    				<a href="history.jsf?page=#{page}" class="pagination">#{page+1}</a>
				  </ui:fragment>

				</ui:repeat>
				
				<ui:fragment rendered="#{history.paginator.page lt (history.paginator.pagesCount-1)}">
  				<a href="history.jsf?page=#{(history.paginator.page+1)}" class="pagination">Next</a>
  			</ui:fragment>
				
		  </div>
				
		</ui:fragment>
		
	</ui:composition>
	
</html>

examples/jsf/pastecode/src/main/webapp/rightMenuDefault.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

	<ui:composition>
			
			<div class="recentPastes">
			  <div class="recentPastesHeader">Recent pastes</div>
			
			  <ui:repeat value="#{recentCodeFragments}" var="codeFragment">
			    <div class="recentPaste">
          	<h:outputLink id="user" value="#{codeFragment.id}">#{codeFragment.user}</h:outputLink>
          	<span class="recentPasteLang">#{codeFragment.language.name}</span><span> | </span>#{codeFragment.friendlyDate}
          </div>		    
			  </ui:repeat>

			</div>
			
	</ui:composition>

</html>

examples/jsf/pastecode/src/main/webapp/template.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core">
    
<f:view>
    <ui:insert name="viewMetadata"/>    
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
  	<title>PasteCode</title>
  	<link rel="stylesheet" href="style/style.css" type="text/css" media="screen" />
    <link REL="SHORTCUT ICON" HREF="favicon.ico"/>
  	<ui:insert name="themes"/>
  	<ui:insert name="head"/>
  	
</head>

<body>
<h:form>

<ui:insert name="myscripts"/>

<div id="header">
  <div id="headerImage"></div>
  
  <div class="divider"></div>
  <div class="menuitem"><a href="home.jsf">new</a></div>
  <div class="divider"></div>
  <div class="menuitem"><a href="history.jsf">history</a></div>
  <div class="divider"></div>    
	<div class="menuitem"><a href="help.jsf">help</a></div>
  <div class="divider"></div>    
  
  <div id="poweredby"></div>
</div>

<div id="topseparator"></div>

<div id="main">

  <div id="rightmenu">
	  <ui:insert name="rightmenu">
		  Menu right
	  </ui:insert>
	</div>
	
  <div id="content">
	  <ui:insert name="mainarea">
		  Main Area
	  </ui:insert>
	</div>

</div>

</h:form>
</body>
</f:view>
</html>